//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neusta.Jira.Connector.Application.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Neusta.Jira.Base.Application.Properties.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This filter could not be loaded..
        /// </summary>
        public static string FilterCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("FilterCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please send request with a non zero id field..
        /// </summary>
        public static string IdIsInvalid {
            get {
                return ResourceManager.GetString("IdIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id will be autogenerated. Please send request without or with an empty id field.
        /// </summary>
        public static string IdIsNotEmpty {
            get {
                return ResourceManager.GetString("IdIsNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to delete this filter..
        /// </summary>
        public static string NotAllowedToDeleteNotOwnFilter {
            get {
                return ResourceManager.GetString("NotAllowedToDeleteNotOwnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to edit this filter..
        /// </summary>
        public static string NotAllowedToEditNotOwnFilter {
            get {
                return ResourceManager.GetString("NotAllowedToEditNotOwnFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects could not be loaded..
        /// </summary>
        public static string ProjectsCouldNotBeLoaded {
            get {
                return ResourceManager.GetString("ProjectsCouldNotBeLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more validation failures have occurred..
        /// </summary>
        public static string ValidationFailuresHaveOccured {
            get {
                return ResourceManager.GetString("ValidationFailuresHaveOccured", resourceCulture);
            }
        }
    }
}
